name: thanks

on:
  issues:
    types: [opened]

  workflow_dispatch:
    inputs:
      issue_number:
        description: "Issue number to test"
        required: true
        type: number

jobs:
  thanks:
    runs-on: ubuntu-latest

    permissions:
      issues: write

    steps:
      - uses: actions/github-script@v9
        id: issue_script
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue_number =
              context.issue.number ||
              Number('${{ inputs.issue_number }}');

            console.log(`issue_number: ${issue_number}`);

            const owner = context.repo.owner;
            const repo = context.repo.repo;

            const issue = await github.rest.issues.get({
              owner,
              repo,
              issue_number
            });

            console.log(`Issue: ${issue.data.title}`);

            const comment = await github.rest.issues.createComment({
              owner,
              repo,
              issue_number,
              body: "Thanks for your contribution!"
            });

            console.log(`comment id: ${comment.data.id}`);

            await github.rest.issues.addLabels({
              owner,
              repo,
              issue_number,
              labels: ['todo-review']
            });

            return comment.data.id;

      - run: echo 'comment id=${{ steps.issue_script.outputs.result }}'